<?php

namespace WellnessLiving\Wl\User\Tracking;

use WellnessLiving\WlModelAbstract;
use WellnessLiving\WlModelRequest;

/**
 * User tracker api to update resolution from frontend.
 *
 * @method WlModelRequest get() This method updates screen resolution.
 * @method WlModelRequest post() Starts or stops tracking.
 * @method WlModelRequest put() Updates tracking of a user flow.
 */
class UserTrackerModel extends WlModelAbstract
{
  /**
   * Current step number.
   * `null` if the number of steps is not set or should not be updated.
   *
   * @put post
   *
   * @var int|null
   */
  public $i_step = null;

  /**
   * Total number of steps.
   * `null` if the number of steps is not set or should not be updated.
   *
   * @put post
   *
   * @var int|null
   */
  public $i_step_all = null;

  /**
   * Tracked user flow ID.
   *
   * @post post
   * @var int
   */
  public $id_flow = 0;

  /**
   * Flag indicating the end of tracking.
   *
   * @post post
   * @var bool
   */
  public $is_end = false;

  /**
   * Flag indicating the start of tracking.
   *
   * @post post
   * @var bool
   */
  public $is_start = false;

  /**
   * Business key.
   *
   * @get get
   * @post get
   * @put get
   *
   * @var string|null
   */
  public $k_business = null;

  /**
   * Session ID to track with.
   * Its value is autogenerated when we call flow start method.
   *
   * @get get
   * @post get,result
   * @put get
   *
   * @var string|null
   */
  public $s_id = null;

  /**
   * Screen resolution in form of width x length.
   * Example: 1024x678.
   *
   * @get get
   * @post get
   *
   * @var string|null
   */
  public $s_resolution = null;

  /**
   * Step of the flow, that the user is now on.
   *
   * @post post
   * @put post
   *
   * @var string
   */
  public $s_step = '';
}

?>