<?php

namespace WellnessLiving\Thoth\PayProcessor\StripeCom\Reporting;

/**
 * Reporting category.
 *
 * @link https://stripe.com/docs/reports/reporting-categories
 *
 * Last used id: 29.
 */
class StripeReportingCategorySid
{
  /**
   * Incrementing available funds for instant payouts.
   *
   * @title Advance
   */
  const ADVANCE = 22;

  /**
   * Decrementing pending funds for instant payouts.
   *
   * @title Advance Funding
   */
  const ADVANCE_FUNDING = 23;

  /**
   * Repayments made to service an anticipation loan in Brazil.
   *
   * @title Anticipation Repayment
   */
  const ANTICIPATION_REPAYMENT = 8;

  /**
   * Charges include payments from cards and from other payment methods.
   *
   * @title Charge
   */
  const CHARGE = 1;

  /**
   * ACH, direct debit, and other asynchronous payment methods remain in a pending state until they either succeed
   * or fail.
   *
   * @title Charge Failure
   */
  const CHARGE_FAILURE = 2;

  /**
   * If one of your connected accounts has a negative balance for 180 days, Stripe transfers a portion of your balance,
   * to zero out that account’s balance.
   *
   * @title Connect Collection Transfer
   */
  const CONNECT_COLLECTION_TRANSFER = 24;

  /**
   * If one of your connected accounts’ balances becomes negative, Stripe temporarily reserves a portion of your
   * balance to ensure that funds can be covered.
   *
   * @title Connect Reserved Funds
   */
  const CONNECT_RESERVED_FUNDS = 25;

  /**
   * Funds contributed via Stripe to a cause (currently Stripe Climate).
   *
   * @title Contribution
   */
  const CONTRIBUTION = 9;

  /**
   * When a customer disputes a charge, Stripe deducts the disputed amount from your balance.
   *
   * @title Dispute
   */
  const DISPUTE = 3;

  /**
   * When a customer disputes a charge, Stripe deducts the disputed amount from your balance.
   *
   * @title Dispute Reversal
   */
  const DISPUTE_REVERSAL = 4;

  /**
   * Fees for Stripe software and services (e.g., for Radar, Connect, Billing, and Identity).
   *
   * @title Fee
   */
  const FEE = 10;

  /**
   * When an issued card is used to make a purchase, an authorization is created.
   *
   * @title Issuing Authorization Hold
   */
  const ISSUING_AUTHORIZATION_HOLD = 18;

  /**
   * When an authorized purchase, made with an issued card, is captured by the merchant, the funds previously held for
   * the authorization
   * {@link StripeReportingCategorySid::ISSUING_AUTHORIZATION_HOLD} are released
   * with a {@link StripeReportingCategorySid::ISSUING_AUTHORIZATION_RELEASE}
   * balance transaction.
   *
   * @title Issuing Authorization Release
   */
  const ISSUING_AUTHORIZATION_RELEASE = 19;

  /**
   * When you dispute an Issuing transaction and funds return to your Stripe balance.
   *
   * @title Issuing Dispute
   */
  const ISSUING_DISPUTE = 20;

  /**
   * When an authorized purchase, made with an issued card, has been authorized and captured by the merchant, an
   * issuing transaction is created, and the purchase amount is deducted from your Stripe balance with an
   * {@link StripeReportingCategorySid::ISSUING_TRANSACTION} balance
   * transaction.
   *
   * @title Issuing Transaction
   */
  const ISSUING_TRANSACTION = 21;

  /**
   * Miscellaneous adjustments to your Stripe balance.
   *
   * @title Other Adjustment
   */
  const OTHER_ADJUSTMENT = 11;

  /**
   * If you are separately authorizing and capturing payments, and you capture an amount less than the initial
   * authorization, you will see a charge for the full authorization amount, and a
   * {@link StripeReportingCategorySid::PARTIAL_CAPTURE_REVERSAL} for
   * the uncaptured portion.
   *
   * @title Partial Capture Reversal
   */
  const PARTIAL_CAPTURE_REVERSAL = 5;

  /**
   * Payouts from your Stripe balance to your bank account.
   *
   * @title Payout
   */
  const PAYOUT = 12;

  /**
   * Funds returned to your balance if a payout fails after it is initially created (e.g., due to an invalid account
   * number or a cancellation).
   *
   * @title Payout Reversal
   */
  const PAYOUT_REVERSAL = 13;

  /**
   * Earnings you’ve generated by collecting platform fees via Stripe Connect charges.
   *
   * @title Platform Earning
   */
  const PLATFORM_EARNING = 26;

  /**
   * Platform fees that you have returned to your connected accounts.
   *
   * @title Platform Earning Refund
   */
  const PLATFORM_EARNING_REFUND = 27;

  /**
   * Payments you’ve refunded to your customers.
   *
   * @title Refund
   */
  const REFUND = 6;

  /**
   * Payments you’ve refunded to your customers.
   *
   * @title Refund Failure
   */
  const REFUND_FAILURE = 7;

  /**
   * When Stripe holds your funds in reserve to mitigate risk, two balance transactions are created: one to debit the
   * funds from your balance, and a second to credit the funds back to your balance at the end of the reserve period.
   *
   * @title Risk Reserved Funds
   */
  const RISK_RESERVED_FUNDS = 14;

  /**
   * Taxes collected by Stripe to be remitted to the appropriate local governments. Typically, this is a tax on
   * Stripe fees.
   *
   * @title Tax
   */
  const TAX = 15;

  /**
   * Funds you transferred into your Stripe balance from your bank account.
   *
   * @title TopUp
   */
  const TOPUP = 16;

  /**
   * If an initially successful top-up fails or is cancelled, the credit to your Stripe balance is reversed.
   *
   * @title TopUp Reversal
   */
  const TOPUP_REVERSAL = 17;

  /**
   * Funds sent from your balance to the balance of your connected accounts.
   *
   * @title Transfer
   */
  const TRANSFER = 28;

  /**
   * Transfers to your connected accounts that have been cancelled.
   *
   * @title Transfer Reversal
   */
  const TRANSFER_REVERSAL = 29;
}

?>