<?php

namespace WellnessLiving\Core\Saml;

/**
 * Name Identifier Format Identifiers.
 *
 * Name identifier formats are listed in section 8.3 of SAML Core specification.
 */
class SamlNameFormatSid
{
  /**
   * Indicates that the content of the element is in the form specified for the contents of the
   * <tt>&lt;ds:X509SubjectName&gt;</tt> element in the XML Signature Recommendation. Implementors should note that the
   * XML Signature specification specifies encoding rules for X.509 subject names that differ from the rules given in
   * IETF RFC 2253.
   *
   * See section 8.3.3 of SAML Core specification for details about this name format.
   */
  const CERTIFICATE = 3;

  /**
   * Indicates that the content of the element is in the form of an email address in the form
   * <tt>local-part@domain</tt>.
   *
   * See section 8.3.2 of SAML Core specification for details about this name format.
   */
  const MAIL = 2;

  /**
   * Indicates that the content of the element is a persistent opaque identifier for a principal that is specific to an
   * identity provider and a service provider or affiliation of service providers. Persistent name identifiers generated
   * by identity providers MUST be constructed using values that have no discernible correspondence with the subject's
   * actual identity (for example, username). They MAY be pseudo-random values, or generated in any other manner,
   * provided there is no guessable relationship between the value and the subject's underlying identity, and that they
   * are unique within the range of values generated by a given identity provider for a given service provider or
   * affiliation of providers. The intent is to create a nonpublic, pair-wise pseudonym to prevent the discovery of the
   * subject's identity or activities. Persistent name identifier values MUST NOT exceed a length of 256 characters.
   * A given value, once associated with a principal, MUST NOT be assigned to a different principal at any time in the
   * future.
   *
   * See section 8.3.7 of SAML Core specification for details about this name format.
   */
  const PERSISTENT = 5;

  /**
   * Indicates that the content of the element is an identifier with transient semantics and SHOULD be treated as an
   * opaque and temporary value by the relying party. Transient identifier values MUST be generated in accordance with
   * the rules for SAML identifiers (see Section 1.3.4), and MUST NOT exceed a length of 256 characters.
   *
   * See section 8.3.8 of SAML Core specification for details about this name format.
   */
  const TRANSIENT = 4;

  /**
   * The interpretation of the content of the element is left to individual implementations.
   *
   * See section 8.3.1 of SAML Core specification for details about this name format.
   */
  const UNSPECIFIED = 1;
}

?>