<?php

namespace WellnessLiving\Wl\AiAgent\Link;

use WellnessLiving\WlModelAbstract;
use WellnessLiving\WlModelRequest;
use WellnessLiving\Wl\Purchase\Item\WlPurchaseItemSid;
use WellnessLiving\Wl\WlServiceSid;

/**
 * Model to send email based on AI agent link action.
 *
 * This endpoint is not public and can be used only by the AI agent.
 *
 * @method WlModelRequest post() Sends an AI agent link action email (booking or purchase) to the specified user.  Triggers the email that the AI agent sends when a client clicks a booking or purchase link  generated by the AI agent chat. Requires the business to have an active AI agent subscription;  the action type determines which notification template is used and which service or purchase  item is referenced in the email body.
 */
class SendMailModel extends WlModelAbstract
{
  /**
   * Purchase item ID. Required if {@link SendMailModel::$text_action} is 'purchase'.
   *
   * One of the {@link WlPurchaseItemSid} constants.
   *
   * @post get
   * @var int
   */
  public $id_purchase_item = 0;

  /**
   * Service ID. Required if {@link SendMailModel::$text_action} is 'booking'.
   *
   * @post get
   * @var int
   * @see WlServiceSid
   */
  public $id_service = 0;

  /**
   * Business key. Required.
   *
   * @post get
   * @var string
   */
  public $k_business = '';

  /**
   * Unique identifier for the link.
   *
   * @post get
   * @var string
   */
  public $k_id = '';

  /**
   * Action type. Must be 'purchase' or 'booking'.
   *
   * @post get
   * @var string
   */
  public $text_action = '';

  /**
   * URL suffix for the link. Optional.
   *
   * @post get
   * @var string
   */
  public $text_url_suffix = '';

  /**
   * User ID. Required.
   *
   * @post get
   * @var string
   */
  public $uid = '';
}

?>