<?php

namespace WellnessLiving\Wl\AiAgent\Phone;

use WellnessLiving\WlModelAbstract;
use WellnessLiving\WlModelRequest;

/**
 * Public endpoint used by the CAASI Phone Agent backend to trigger the "Phone Agent Call Received" staff
 * notification, immediately after a Phone Agent call concludes, regardless of outcome (resolved by CAASI,
 * transferred live, or callback requested).
 *
 * @method WlModelRequest post() {@inheritdoc}  Sends the "Phone Agent Call Received" staff notification to every active staff member of the business who has the {@link \Wl\Privilege\PrivilegeSid::NOTIFICATION_PHONE_AGENT_CALL_RECEIVED} permission.  Requires the business to have an active Phone Agent subscription tier.
 */
class CallReceivedModel extends WlModelAbstract
{
  /**
   * How the call ended. Required.
   *
   * @post get
   * @var int
   * @see CallOutcomeEnum
   */
  public $id_call_outcome = 0;

  /**
   * Business key. Required.
   *
   * @post get
   * @var string
   */
  public $k_business = '';

  /**
   * Short summary of the call generated by CAASI. Used in the email notification only. Optional.
   *
   * @post get
   * @var string
   */
  public $text_call_summary = '';

  /**
   * The caller's name, if identified. Optional.
   *
   * @post get
   * @var string
   */
  public $text_caller_name = '';

  /**
   * The caller's phone number. Optional.
   *
   * @post get
   * @var string
   */
  public $text_caller_phone = '';

  /**
   * URL to view the conversation between the caller and CAASI (for email). Optional.
   *
   * @post get
   * @var string
   */
  public $url_view_conversation_link = '';

  /**
   * URL to view the conversation, in an SMS-safe format. Optional.
   *
   * @post get
   * @var string
   */
  public $url_view_conversation_link_sms = '';
}

?>