<?php

namespace WellnessLiving\Wl\ClassPass;

use WellnessLiving\WlModelAbstract;
use WellnessLiving\WlModelRequest;

/**
 * Api endpoint used to check appointment reservation state.
 *
 * ## Dispatched URL:
 * * <tt>/cp/v1/partners/{partner_id}/venues/{venue_id}/appointments/{appointment_id}/attendance</tt>
 *
 * @method WlModelRequest delete()
 * @method WlModelRequest get() Gets appointment reservation state.
 * @method WlModelRequest patch()
 * @method WlModelRequest post()
 * @method WlModelRequest put() This method is called to process <tt>PUT</tt> query.
 */
class AppointmentAttendanceModel extends WlModelAbstract
{
  /**
   * List of appointment attendees.
   *
   * _Basically here will be only one attendee because <tt>Wellnessliving</tt>
   * do not support multiple attendees for one appointment ID._
   *
   * @field attendance
   * @get result
   * @var AppointmentAttendanceEntity[]
   */
  public $a_attendance;

  /**
   * Appointment reservation identifier generated by <tt>Classpass</tt>.
   *
   * @get get
   * @var string
   */
  public $s_appointment_id;

  /**
   * Partner ID.
   *
   * @get get
   * @var string
   */
  public $s_partner_id;

  /**
   * Venue ID.
   *
   * @get get
   * @var string
   */
  public $s_venue_id;
}

?>